<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="10616" started-at="2022-07-28T21:19:10 IST" finished-at="2022-07-28T21:19:20 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="10616" started-at="2022-07-28T21:19:10 IST" finished-at="2022-07-28T21:19:20 IST">
      <class name="regression.LoginFunctionality">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:regression.LoginFunctionality@6acdbdf5]" name="beforeSuite" is-config="true" duration-ms="160" started-at="2022-07-28T21:19:09 IST" finished-at="2022-07-28T21:19:10 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="beforeClassOfA()[pri:0, instance:regression.LoginFunctionality@6acdbdf5]" name="beforeClassOfA" is-config="true" duration-ms="8973" started-at="2022-07-28T21:19:10 IST" finished-at="2022-07-28T21:19:19 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClassOfA -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:regression.LoginFunctionality@6acdbdf5]" name="beforeMethod" is-config="true" duration-ms="3" started-at="2022-07-28T21:19:19 IST" finished-at="2022-07-28T21:19:19 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void regression.LoginFunctionality.verifyUsercanLogin()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="verifyUsercanLogin()[pri:1, instance:regression.LoginFunctionality@6acdbdf5]" name="verifyUsercanLogin" duration-ms="11" started-at="2022-07-28T21:19:19 IST" finished-at="2022-07-28T21:19:19 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUsercanLogin -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:regression.LoginFunctionality@6acdbdf5]" name="afterMethod" is-config="true" duration-ms="21" started-at="2022-07-28T21:19:19 IST" finished-at="2022-07-28T21:19:19 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyUsercanLogin status=SUCCESS method=LoginFunctionality.verifyUsercanLogin()[pri:1, instance:regression.LoginFunctionality@6acdbdf5] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:regression.LoginFunctionality@6acdbdf5]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2022-07-28T21:19:19 IST" finished-at="2022-07-28T21:19:19 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void regression.LoginFunctionality.verifyUsercanAddBrand()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="verifyUsercanAddBrand()[pri:2, instance:regression.LoginFunctionality@6acdbdf5]" name="verifyUsercanAddBrand" duration-ms="3" started-at="2022-07-28T21:19:19 IST" finished-at="2022-07-28T21:19:19 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[User can not add new brand in system expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: User can not add new brand in system expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at regression.LoginFunctionality.verifyUsercanAddBrand(LoginFunctionality.java:20)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUsercanAddBrand -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:regression.LoginFunctionality@6acdbdf5]" name="afterMethod" is-config="true" duration-ms="291" started-at="2022-07-28T21:19:19 IST" finished-at="2022-07-28T21:19:19 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyUsercanAddBrand status=FAILURE method=LoginFunctionality.verifyUsercanAddBrand()[pri:2, instance:regression.LoginFunctionality@6acdbdf5] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:regression.LoginFunctionality@6acdbdf5]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2022-07-28T21:19:19 IST" finished-at="2022-07-28T21:19:19 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void regression.LoginFunctionality.verifyUsercanInventory()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="verifyUsercanInventory()[pri:3, instance:regression.LoginFunctionality@6acdbdf5]" name="verifyUsercanInventory" duration-ms="7" started-at="2022-07-28T21:19:19 IST" finished-at="2022-07-28T21:19:19 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at regression.LoginFunctionality.verifyUsercanInventory(LoginFunctionality.java:27)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUsercanInventory -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:regression.LoginFunctionality@6acdbdf5]" name="afterMethod" is-config="true" duration-ms="261" started-at="2022-07-28T21:19:19 IST" finished-at="2022-07-28T21:19:19 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyUsercanInventory status=FAILURE method=LoginFunctionality.verifyUsercanInventory()[pri:3, instance:regression.LoginFunctionality@6acdbdf5] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:regression.LoginFunctionality@6acdbdf5]" name="afterClass" is-config="true" duration-ms="980" started-at="2022-07-28T21:19:19 IST" finished-at="2022-07-28T21:19:20 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method status="PASS" signature="afterSuiteMethod()[pri:0, instance:regression.LoginFunctionality@6acdbdf5]" name="afterSuiteMethod" is-config="true" duration-ms="442" started-at="2022-07-28T21:19:20 IST" finished-at="2022-07-28T21:19:21 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuiteMethod -->
      </class> <!-- regression.LoginFunctionality -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
